CREATE TABLE "NPS02"."QLTRCS_WAVE_BP" (
    "SRVY_ID" INTEGER NOT NULL,
    "SRVY_RESP_DT" DATE,
    "TOCHPNT_TYPE" VARCHAR(100 OCTETS),
    "REASONS_FOR_SCORE" VARCHAR(4000 CODEUNITS32),
    "FINAL_COMMENTS" VARCHAR(4000 CODEUNITS32),
    "CREATED_BY" VARCHAR(128 OCTETS),
    "CREATED_AT" TIMESTAMP,
    "UPDATED_BY" VARCHAR(128 OCTETS),
    "UPDATED_AT" TIMESTAMP
) ORGANIZE BY ROW;